name: edgard_in_kimeria
description: Edgard in Kimeria.
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flame: ^1.32.0
  flame_tiled: ^3.0.7
  flame_audio: ^2.11.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  shaders:
    - shaders/bomb_explosion.frag
    - shaders/chroma_glitch.frag
    - shaders/fog.frag
    - shaders/ripple.frag
    - shaders/shockwave.frag
  assets:
    - assets/
    - assets/tiles/
    - assets/images/
    - assets/images/background/
    - assets/images/Tileset/
    - assets/images/hero/
    - assets/images/HUD/
    - assets/images/enemy/
    - assets/images/objects/
    # - assets/images/enemy/boss/
    # - assets/images/player/
    # - assets/images/items/
    # - assets/images/tiled/
    - assets/audio/
    # - resources/lang/en.json
    # - resources/lang/ru.json

  # fonts:
  #  - family: Normal
  #    fonts:
  #      - asset: fonts/font_pixel.ttf
